project:
  type: website

website:
  title: "Geospatial Research Lab"
  navbar:
    logo-href: about.qmd
    
    left:
      - href: https://www.american.edu/library/technology/geospatial/
        text: Home
      - href: workshops.qmd
        text: Workshops
      - href: https://subjectguides.library.american.edu/gis/home
        text: "LibGuide"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



